baseURL = 'https://pragmatic.recipes/'
languageCode = 'en-us'
title = 'Pragmatic Recipes'
theme = "smol"

# Parameters
[params]
    subtitle = "Get your recipes pragmatically"
    dateFmt = "2006.02.01 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "food"
        name = "Food"
        url = "/food/"
        weight = 1 

  [[menu.main]]
	identifier = "drinks"
	name = "Drinks"
	url = "/drinks/"
	weight = 2

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 4

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/rodabaugh/pragmatic-recipes"
        weight = 1
